Auth/urls.py
from Auth import views
from django.urls import path

app_name = 'Auth'
urlpatterns = [
    path('', views.index, name = 'Index'),
    path('login/', views.login, name = 'Login'),
    path('register/', views.register, name = 'Register'),
    path('register/user/', views.register_user, name='Register User'),
    path('register/admin/', views.register_admin, name='Register Admin'),
    path('logout/', views.logout_user, name = 'Logout'),
    path('profile/', views.ProfilePemain, name = 'Profile'),
    path('profile-admin/', views.ProfileAdmin, name = 'ProfileAdmin')
    ]

ReadPaskalis/urls.py
from ReadPaskalis import views
from django.urls import path

app_name = 'ReadPaskalis'
urlpatterns = [
    path('warna-kulit/', views.getWarnaKulit, name = 'Warna Kulit'),
    path('level/', views.getLevel, name = 'Level'),
    path('menggunakan-apparel/', views.getMenggunakanApparel, name = 'Menggunakan Apparel'),
    path('menggunakan-apparel/create/', views.createMenggunakanApparel, name = 'Create Menggunakan Apparel'),
    path('menggunakan-apparel/delete/<str:id>', views.deleteMenggunakanApparel, name = 'Delete Menggunakan Apparel'),
    path('warna-kulit/create/', views.createWarnaKulit, name = 'Create Warna Kulit'),
    path('warna-kulit/delete/<str:kode>', views.deleteWarnaKulit, name = 'Delete Warna Kulit'),
    path('level/create/', views.createLevel, name = 'Create Level'),
    path('level/update/<int:level>', views.updateLevel, name = 'Update Level'),
    path('level/delete/<int:level>', views.deleteLevel, name = 'Delete Level'),
    ]

TKBasdatD01/urls.py
from django.contrib import admin
from django.urls import path, include

import Auth, ReadBintangNS, ReadPaskalis
import Auth, ReadBintangNS, ReadBisma

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Auth.urls', namespace="mainApp")),
    path('home/', Auth.views.index, name = 'Index'),
    path('', include('ReadBintangNS.urls', namespace="mainApp2")),
    path('', include('ReadPaskalis.urls', namespace="mainApp3")),
    path('', include('ReadBisma.urls', namespace="mainApp4"))
]

ReadPaskalis/models.py
from django.db import models

# Create your models here.

ReadPaskalis/views.py
from django.shortcuts import render
from Auth.views import *
from Auth.urls import *
from django.shortcuts import render, redirect
import django.db as db
from django.db import connection
# Create your views here.

def getWarnaKulit(request):
    userUsername = checkLoggedIn(request)

    if not userUsername:
        return redirect('mainApp:Index')

    if not cekAdmin(request, userUsername):

        return redirect('/')

    cursor = connection.cursor()
    cursor.execute("set search_path to the_cims")

    cursor.execute("SELECT * FROM WARNA_KULIT")
    warna_kulit = cursor.fetchall()


    return render(request, 'WarnaKulit.html', {'warna_kulit' : warna_kulit})

def getLevel(request):
    userUsername = checkLoggedIn(request)

    if not userUsername:
        return redirect('mainApp:Index')

    if not cekAdmin(request, userUsername):

        return redirect('/')

    cursor = connection.cursor()
    cursor.execute("set search_path to the_cims")

    cursor.execute("SELECT * FROM LEVEL ORDER BY level ASC")
    level = cursor.fetchall()


    return render(request, 'Level.html', {'level' : level})

def getMenggunakanApparel(request):
    userUsername = checkLoggedIn(request)

    if not userUsername:
        return redirect('mainApp:Index')

    if not cekAdmin(request, userUsername):

        return redirect('/')

    cekRole = request.session['username']
    role = cekAdmin(request, cekRole)

    if role == "Admin":

        cursor = connection.cursor()
        cursor.execute("set search_path to the_cims")

        cursor.execute("SELECT MA.username_pengguna, MA.nama_tokoh, KJB.nama ,A.warna_apparel, A.nama_pekerjaan, A.kategori_apparel FROM MENGGUNAKAN_APPAREL MA, APPAREL A, KOLEKSI_JUAL_BELI KJB WHERE MA.id_koleksi = A.id_koleksi AND KJB.id_koleksi = A.id_koleksi")
        apparel = cursor.fetchall()

    elif role == "Pemain":

        cursor = connection.cursor()
        cursor.execute("set search_path to the_cims")

        cursor.execute("SELECT MA.username_pengguna, MA.nama_tokoh, KJB.nama ,A.warna_apparel, A.nama_pekerjaan, A.kategori_apparel, A.id_koleksi FROM MENGGUNAKAN_APPAREL MA, APPAREL A, KOLEKSI_JUAL_BELI KJB WHERE MA.id_koleksi = A.id_koleksi AND KJB.id_koleksi = A.id_koleksi AND MA.username_pengguna = %s", [cekRole])
        apparel = cursor.fetchall()

    return render(request, 'MenggunakanApparel.html', {'apparel' : apparel})

def createWarnaKulit(request):
    userUsername = checkLoggedIn(request)
    cekRole = request.session['username']
    role = cekAdmin(request, cekRole)
    data = request.POST
    response = {}

    if not userUsername:
        return redirect('mainApp:Index')

    if role == "Pemain":

        return redirect('/warna-kulit/')

    else:

        if request.method == 'POST':
            message = " "
            kode = data['kode']

            try:
                cursor = connection.cursor()
                cursor.execute("set search_path to the_cims")
                cursor.execute(
                    "INSERT INTO WARNA_KULIT VALUES (%s)", [kode]
                )
                message = "Warna Kulit berhasil ditambahkan!"

            except db.Error as e:
                message = e

            return render(request, 'CreateWarnaKulit.html', {'message' : message})

        else:

            return render(request, 'CreateWarnaKulit.html', response)

def createLevel(request):
    userUsername = checkLoggedIn(request)
    cekRole = request.session['username']
    role = cekAdmin(request, cekRole)
    data = request.POST
    response = {}

    if not userUsername:
        return redirect('mainApp:Index')

    if role == "Pemain":

        return redirect('/level/')

    else:

        if request.method == 'POST':
            message = " "
            level = int(data['level'])
            xp = int(data['xp'])

            try:
                cursor = connection.cursor()
                cursor.execute("set search_path to the_cims")
                cursor.execute(
                    "INSERT INTO LEVEL VALUES (%s, %s)", [level, xp]
                )
                message = "Level berhasil ditambahkan!"

            except db.Error as e:
                message = e

            return render(request, 'CreateLevel.html', {'message' : message})

        else:

            return render(request, 'CreateLevel.html', response)

def updateLevel(request, level):

    userUsername = checkLoggedIn(request)
    cekRole = request.session['username']
    role = cekAdmin(request, cekRole)
    data = request.POST

    if not userUsername:
        return redirect('mainApp:Index')

    if role == "Pemain":

        return redirect('/level/')

    else:

        if request.method == 'POST':
            message = " "
            xp = int(data['xp'])

            try:
                cursor = connection.cursor()
                cursor.execute("set search_path to the_cims")
                cursor.execute(
                "UPDATE LEVEL set xp = %s where level = %s", [xp, level]
            )
                message = "Level berhasil diupdate!"

            except db.Error as e:
                message = e

            return render(request, 'UpdateLevel.html', {'message' : message, 'level': level})

        else:

            return render(request, 'UpdateLevel.html', {'level': level})

    
def deleteWarnaKulit(request, kode):
    cekRole = request.session['username']
    role = cekAdmin(request, cekRole)

    message = " "

    if role == "Pemain":

        return redirect('/menggunakan-apparel/')

    message = " "
    kodeWarna = "#" + kode

    try:
        cursor = connection.cursor()
        cursor.execute("set search_path to the_cims")
        cursor.execute(
            "DELETE FROM WARNA_KULIT WHERE kode = %s", [kodeWarna]
        )
        message = "Warna Kulit berkode " + kodeWarna + " berhasil dihapus!"

    except db.Error as e:
        message = e

    userUsername = checkLoggedIn(request)

    if not userUsername:
        return redirect('mainApp:Index')

    if not cekAdmin(request, userUsername):

        return redirect('/')

    cursor = connection.cursor()
    cursor.execute("set search_path to the_cims")

    cursor.execute("SELECT * FROM WARNA_KULIT")
    warna_kulit = cursor.fetchall()


    return render(request, 'WarnaKulit.html', {'warna_kulit' : warna_kulit , 'message' : message})

def deleteLevel(request, level):
    cekRole = request.session['username']
    role = cekAdmin(request, cekRole)

    message = " "

    if role == "Pemain":

        return redirect('/menggunakan-apparel/')

    try:
        cursor = connection.cursor()
        cursor.execute("set search_path to the_cims")
        cursor.execute(
            "DELETE FROM LEVEL WHERE level = %s", [level]
        )
        message = "Level " + str(level) + " berhasil dihapus"

    except db.Error as e:
        message = e

    return redirect('/level/')

def createMenggunakanApparel(request):
    userUsername = checkLoggedIn(request)
    cekRole = request.session['username']
    role = cekAdmin(request, cekRole)
    data = request.POST
    response = {}

    if not userUsername:
        return redirect('mainApp:Index')

    if role == "Admin":

        return redirect('/menggunakan-apparel/')

    else:

        cursor = connection.cursor()
        cursor.execute("set search_path to the_cims")

        cursor.execute("SELECT * FROM TOKOH WHERE username_pengguna = %s", [cekRole])
        tokoh = cursor.fetchall()
        response['tokoh'] = tokoh

        cursor.execute("SELECT * FROM APPAREL")
        apparel = cursor.fetchall()
        response['apparel'] = apparel

        if request.method == 'POST':
            message = " "
            tokoh = data["nama_tokoh"]
            apparel = data["id_koleksi"]

            try:
                cursor = connection.cursor()
                cursor.execute("set search_path to the_cims")
                cursor.execute(
                    "INSERT INTO MENGGUNAKAN_APPAREL VALUES (%s, %s, %s)", [cekRole, tokoh, apparel]
                )
                message = str(tokoh) + " berhasil menggunakan apparel dengan id " + str(apparel)

            except db.Error as e:
                message = e

            return render(request, 'CreateMenggunakanApparel.html', {'message' : message})

        else:

            return render(request, 'CreateMenggunakanApparel.html', response)

def deleteMenggunakanApparel(request, id):
    cekRole = request.session['username']
    role = cekAdmin(request, cekRole)

    if role == "Admin":

        return redirect('/menggunakan-apparel/')

    message = " "

    try:
        cursor = connection.cursor()
        cursor.execute("set search_path to the_cims")
        cursor.execute(
            "DELETE FROM MENGGUNAKAN_APPAREL WHERE id_koleksi = %s AND username_pengguna = %s", [id, cekRole]
        )
        message = "Apparel dengan id " + str(id) + " berhasil dilepas"

    except db.Error as e:
        message = e

    return redirect('/menggunakan-apparel/')

    

ReadPaskalis/templates/CreateLevel.html
{% load static %}
{% block css %}
{% endblock %}
{% block title %}
<title>Create Level</title>
{% endblock title %}
<body>
{% include 'navbar.html' %}
    <div style="padding: 10px;" id="content">
        {% if request.session.role == 'Admin' %}
        <h3>Tambah Level</h3>
        <form action="" method="POST">
            {% csrf_token %}
            <p><b>Informasi Level:</b></p>
            <label for="nama_tokoh">Level: </label>
            <input type="text" name="level" id="level" required><br>

            <label for="nama_tokoh">XP: </label>
            <input type="text" name="xp" id="xp" required><br>

            <div style="padding-top: 10px;" id='button-wrapper'>
                <button id="submit" type="submit">Tambahkan</button>
            </div>
            <h2 style="color: red; text-align: center;">{{message}}</h2>
            <div>
        </form>
        {% else %}
        <h4>Anda tidak punya akses ke halaman ini!</h4>
        {% endif %}
    </div>
</body>
</html>

ReadPaskalis/templates/CreateMenggunakanApparel.html
{% load static %}
{% block css %}
{% endblock %}
{% block title %}
<title>Create Menggunakan Apparel</title>
{% endblock title %}
<body>
{% include 'navbar.html' %}
    <div style="padding: 10px;" id="content">
        {% if request.session.role == 'Pemain' %}
        <h3>Tambah Menggunakan Apparel</h3>
        <form action="" method="POST">
            {% csrf_token %}
            <p><b>Informasi Menggunakan Apparel:</b></p>
            <label for="nama_tokoh">Nama Tokoh: </label>
            <select class="form-control" name="nama_tokoh" id="nama_tokoh">
                {%for i in tokoh %}
                <option value="{{i.1}}">{{i.1}}</option>
                {% endfor %}
            </select><br>

            <label for="id_koleksi">ID Koleksi Apparel: </label>
            <select class="form-control" name="id_koleksi" id="id_koleksi">
                {%for i in apparel %}
                <option value="{{i.0}}">{{i.0}}</option>
                {% endfor %}
            </select><br>

            <div style="padding-top: 10px;" id='button-wrapper'>
                <button id="submit" type="submit">Pakai</button>
            </div>

            <h2 style="color: red; text-align: center;">{{message}}</h2>
            <div>
        </form>
        {% else %}
        <h4>Anda tidak punya akses ke halaman ini!</h4>
        {% endif %}
    </div>
</body>
</html>

ReadPaskalis/templates/CreateWarnaKulit.html
{% load static %}
{% block css %}
{% endblock %}
{% block title %}
<title>Create Warna</title>
{% endblock title %}
<body>
{% include 'navbar.html' %}
    <div style="padding: 10px;" id="content">
        {% if request.session.role == 'Admin' %}
        <h3>Tambah Warna Kulit</h3>
        <form action="" method="POST">
            {% csrf_token %}
            <p><b>Informasi Warna:</b></p>
            <label for="nama_tokoh">Kode Warna</label><br>
            <input type="color" name="kode" id="kode" value="#ff0000">
            <div style="padding-top: 10px;" id='button-wrapper'>
                <button id="submit" type="submit">Tambahkan</button>
            </div>
            <h2 style="color: red; text-align: center;">{{message}}</h2>
            <div>
        </form>
        {% else %}
        <h4>Anda tidak punya akses ke halaman ini!</h4>
        {% endif %}
    </div>
</body>
</html>

ReadPaskalis/templates/Level.html
{% load static %}


{% block css %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
{% endblock %}


{% block title %}
<title>Warna Kulit</title>
{% endblock title %}

<body>
{% include 'navbar.html' %}
    <div id="content">
        <h3>Level</h3>
        <div style="display: block">
            {% if request.session.role == 'Admin' %}
                <a href="create/">Create Level</a>
            {% endif %}
            <table class ="table">
                <thead>
                    <tr>
                        <th scope ="col">No</th>
                        <th scope ="col">Level</th>
                        <th scope ="col">XP</th>
                    </tr>
                </thead>
                <tbody>
                    {% if level %}
                        {% for i in level %}
                            <tr id="myUL">
                                <td>{{ forloop.counter }}</td>
                                <td>{{ i.0 }}</td>
                                <td>{{ i.1 }}</td>
                                <td>
                                    {% if request.session.role == 'Admin' %}
                                        <a href="update/{{ i.0 }}">Update</a>
                                        <a href="delete/{{ i.0 }}">Delete</a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
        <div>
            <h2 style="color: red; text-align: center;">{{ message }}</h2>
        </div>
</body>
</html>

ReadPaskalis/templates/MenggunakanApparel.html
{% load static %}


{% block css %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
{% endblock %}


{% block title %}
<title>Menggunakan Apparel</title>
{% endblock title %}

<body>
{% include 'navbar.html' %}
    <div id="content">
        <h3>Menggunakan Apparel</h3>
        <div style="display: block">
            {% if request.session.role == 'Pemain' %}
            <a href="create/">Create Menggunakan Apparel</a>
            {% endif %}
            <table class ="table">
                <thead>
                    <tr>
                        <th scope ="col">No</th>
                        {% if request.session.role == 'Admin' %}
                            <th scope ="col">Username Pemain</th>
                        {% endif %}
                        <th scope ="col">Nama Tokoh</th>
                        <th scope ="col">Nama Apparel</th>
                        <th scope ="col">Warna</th>
                        <th scope ="col">Nama Pekerjaan</th>
                        <th scope ="col">Kategori</th>
                        {% if request.session.role == 'Pemain' %}
                            <th scope ="col">Action</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% if apparel %}
                        {% for i in apparel %}
                            <tr id="myUL">
                                <td>{{ forloop.counter }}</td>
                                {% if request.session.role == 'Admin' %}
                                    <td>{{ i.0 }}</td>
                                {% endif %}
                                <td>{{ i.1 }}</td>
                                <td>{{ i.2 }}</td>
                                <td>{{ i.3 }}</td>
                                <td>{{ i.4 }}</td>
                                <td>{{ i.5 }}</td>
                                <td>
                                    {% if request.session.role == 'Pemain' %}
                                        <a href="delete/{{ i.6 }}">Lepas</a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
        <div>
            <h2 style="color: red; text-align: center;">{{ message }}</h2>
        </div>
</body>
</html>

ReadPaskalis/templates/UpdateLevel.html
{% load static %}
{% block css %}
{% endblock %}
{% block title %}
<title>Create Level</title>
{% endblock title %}
<body>
{% include 'navbar.html' %}
    <div style="padding: 10px;" id="content">
        {% if request.session.role == 'Admin' %}
        <h3>Tambah Level</h3>
        <form action="" method="post">
            {% csrf_token %}
            <p><b>Informasi Level:</b></p>
            <label for="nama_tokoh">Level: {{ level }}</label><br>

            <label for="nama_tokoh">XP: </label>
            <input type="text" name="xp" id="xp" required><br>

            <div style="padding-top: 10px;" id='button-wrapper'>
                <button id="submit" type="submit">Tambahkan</button>
            </div>
            <h2 style="color: red; text-align: center;">{{ message }}</h2>
            <div>
        </form>
        {% else %}
        <h4>Anda tidak punya akses ke halaman ini!</h4>
        {% endif %}
    </div>
</body>
</html>

ReadPaskalis/templates/WarnaKulit.html
{% load static %}


{% block css %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
{% endblock %}


{% block title %}
<title>Warna Kulit</title>
{% endblock title %}

<body>
{% include 'navbar.html' %}
    <div id="content">
        <h3>Warna Kulit</h3>
        <div style="display: block">
            {% if request.session.role == 'Admin' %}
                <a href="create/">Create Warna Kulit</a>
            {% endif %}
            <table class ="table">
                <thead>
                    <tr>
                        <th scope ="col">No</th>
                        <th scope ="col">Kode</th>
                    </tr>
                </thead>
                <tbody>
                    {% if warna_kulit %}
                        {% for i in warna_kulit %}
                            <tr id="myUL">
                                <td>{{ forloop.counter }}</td>
                                <td>{{ i.0 }}</td>
                                <td>
                                    {% if request.session.role == 'Admin' %}
                                        <a href="delete/{{ i.0|slice:'1:' }}">Delete</a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
        <div>
            <h2 style="color: red; text-align: center;">{{ message }}</h2>
        </div>
</body>
</html>

ReadPaskalis/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">The Cims</a>
    </div>
    <ul class="nav navbar-nav">
      <li ><a href="/">Home</a></li>
      <li><a href="/bekerja">Bekerja</a></li>
      <li><a href="/pekerjaan">Pekerjaan</a></li>
      <li><a href="/menggunakan-barang">Menggunakan Barang</a></li>
      <li><a href="/warna-kulit">Warna Kulit</a></li>
      <li><a href="/level">Level</a></li>
      <li><a href="/menggunakan-apparel">Menggunakan Apparel</a></li>
        {% if request.session.username %}
            <li class='nav-item'>
                <a href="{% url 'mainApp:Logout' %}">
                    <button type='button' class='btn btn-success btn-md'>Keluar</button>
                </a>
            </li>
        {% else %}
            <li class='nav-item'>
                <a href="{% url 'mainApp:Login' %}">
                    <button type='button' class='btn btn-success btn-md'>Masuk</button>
                </a>
            </li>
        {% endif %}
    </ul>
  </div>
</nav>

</body>
</html>